# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@aws-sdk/client-bedrock-runtime"]

# --- API FIRST (must be above the SPA catch-all) ---
# One wildcard covers all /agent/* endpoints
[[redirects]]
  from = "/agent/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# (Optional: the explicit mappings below are redundant with the wildcard,
# but safe to keep if you like the clarity.)

[[redirects]]
  from = "/agent/chat"
  to = "/.netlify/functions/agent-chat"
  status = 200

[[redirects]]
  from = "/agent/fetch-url"
  to = "/.netlify/functions/agent-fetch-url"
  status = 200

[[redirects]]
  from = "/agent/summarize"
  to = "/.netlify/functions/agent-summarize"
  status = 200

# --- SPA CATCH-ALL MUST BE LAST ---
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
