service: clarityarmor-agent
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev

  # HTTP API (API Gateway v2) CORS goes here (not at the function level)
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
        - https://clarityarmor.com
      allowedHeaders:
        - Content-Type
      allowedMethods:
        - OPTIONS
        - GET
        - POST
      allowCredentials: false

  # Basic Lambda execution role bits (Serverless will create/attach)
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  analyze:
    handler: handler.analyze
    events:
      - httpApi:
          path: /agent/analyze
          method: POST

