service: tsca-agent
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION, 'us-east-1'}
  memorySize: 256
  timeout: 15
  httpApi:
    cors: true
  environment:
    NODE_OPTIONS: --enable-source-maps
    BEDROCK_MODEL_ID: ${env:BEDROCK_MODEL_ID, ''}
    BEDROCK_REGION: ${env:BEDROCK_REGION, 'us-east-1'}

iam:
  role:
    statements:
      - Effect: Allow
        Action:
          - bedrock:InvokeModel
        Resource: "*"

functions:
  chat:
    handler: dist/handlers/chat.handler
    events:
      - httpApi:
          method: POST
          path: /agent/chat
  fetchUrl:
    handler: dist/handlers/fetch_url.handler
    events:
      - httpApi:
          method: POST
          path: /agent/fetch-url

package:
  patterns:
    - '!**/*'
    - 'dist/**'
    - 'node_modules/**'
    - 'package.json'

plugins:
  - serverless-offline
