service: tsca-agent
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION, 'us-east-1'}
  memorySize: 256
  timeout: 15
  httpApi:
    cors: true
  provider:
  environment:
    NODE_OPTIONS: --enable-source-maps
    BEDROCK_MODEL_ID: ${env:BEDROCK_MODEL_ID, 'anthropic.claude-3-5-sonnet-20240620-v1:0'}
    BEDROCK_REGION:   ${env:BEDROCK_REGION, 'us-east-1'}
    BEDROCK_MAX_TOKENS: ${env:BEDROCK_MAX_TOKENS, '96'}
    BEDROCK_TEMPERATURE: ${env:BEDROCK_TEMPERATURE, '0.4'}
    BEDROCK_TOP_P: ${env:BEDROCK_TOP_P, '0.9'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
          Resource: "*"

functions:
  chat:
    handler: dist/handlers/chat.handler
    events:
      - httpApi:
          method: POST
          path: /agent/chat
  fetchUrl:
    handler: dist/handlers/fetch_url.handler
    events:
      - httpApi:
          method: POST
          path: /agent/fetch-url
  analyze:
    handler: dist/handlers/analyze.handler
    events:
      - httpApi:
          method: POST
          path: /agent/analyze

package:
  patterns:
    - '!**/*'
    - 'dist/**'
    - 'node_modules/**'
    - 'package.json'

plugins:
  - serverless-offline

