service: clarityarmor-agent
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 512
  timeout: 15
  environment:
    LOG_LEVEL: info
  iam:
    role:
      statements:
        # Uncomment when you wire Bedrock/DynamoDB:
        # - Effect: Allow
        #   Action:
        #     - bedrock:InvokeModel
        #   Resource: "*"
        # - Effect: Allow
        #   Action:
        #     - dynamodb:PutItem
        #   Resource: "*"

functions:
  analyze:
    handler: handler.analyze
    events:
      - httpApi:
          path: /agent/analyze
          method: POST
          cors:
            allowedOrigins:
              - https://clarityarmor.com
              - http://localhost:5173
            allowedHeaders:
              - content-type
            allowedMethods:
              - POST
            allowCredentials: false
