service: tsca-agent
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION, 'us-east-1'}
  memorySize: 256
  timeout: 15
  httpApi:
    cors: true
  environment:
    NODE_OPTIONS: --enable-source-maps
    BEDROCK_REGION: ${env:BEDROCK_REGION, 'us-east-1'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
          Resource: "*"

functions:
  chat:
    handler: dist/handlers/chat.handler
    environment:
      BEDROCK_MODEL_ID: ${env:CHAT_MODEL_ID, 'anthropic.claude-3-5-sonnet-20240620-v1:0'}
    events:
      - httpApi:
          method: POST
          path: /agent/chat

  analyze:
    handler: dist/handlers/analyze.handler
    environment:
      BEDROCK_MODEL_ID: ${env:ANALYZE_MODEL_ID, 'anthropic.claude-3-haiku-20240307-v1:0'}
    events:
      - httpApi:
          method: POST
          path: /agent/analyze

  fetchUrl:
    handler: dist/handlers/fetch_url.handler
    events:
      - httpApi:
          method: POST
          path: /agent/fetch-url

package:
  patterns:
    - '!**/*'
    - 'dist/**'
    - 'node_modules/**'
    - 'package.json'

plugins:
  - serverless-offline

