service: clarityarmor-agent

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  memorySize: 512
  timeout: 10
  httpApi:
    cors:
      allowedOrigins:
        - https://clarityarmor.com
        - http://localhost:5173
      allowedHeaders:
        - Content-Type
      allowedMethods:
        - OPTIONS
        - POST
      allowCredentials: false
      maxAge: 86400
  environment:
    ALLOWED_ORIGINS: 'https://clarityarmor.com,http://localhost:5173'

functions:
  analyze:
    handler: handler.analyze
    events:
      - httpApi:
          path: /agent/analyze
          method: post

  summarize:
    handler: handler.summarize
    events:
      - httpApi:
          path: /agent/summarize
          method: post

  chat:
    handler: handler.chat
    events:
      - httpApi:
          path: /agent/chat
          method: post

