import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { BookOpen, ShieldCheck, Landmark, Cpu, Trophy, Search, Beaker, Brain, HelpCircle } from "lucide-react";
import BackButton from "@/components/BackButton";
const Card = ({ to, title, desc, icon }) => (_jsxs(Link, { to: to, className: "block rounded-2xl p-6 bg-[#e9eef5] hover:scale-[1.01] transition", style: { boxShadow: "inset 6px 6px 12px #cfd6e0, inset -6px -6px 12px #ffffff" }, children: [_jsxs("div", { className: "flex items-center gap-3", children: [icon, _jsx("h3", { className: "text-lg font-semibold text-slate-900", children: title })] }), _jsx("p", { className: "mt-2 text-sm text-slate-700", children: desc })] }));
const EducateHub = () => {
    return (_jsx("div", { className: "min-h-screen bg-[#e9eef5] py-10", children: _jsxs("div", { className: "max-w-6xl mx-auto px-6", children: [_jsx(BackButton, {}), _jsxs("div", { className: "rounded-3xl p-8 md:p-10", style: {
                        background: "#e9eef5",
                        boxShadow: "9px 9px 18px rgba(163,177,198,0.6), -9px -9px 18px rgba(255,255,255,0.9)",
                    }, children: [_jsx("h1", { className: "text-3xl font-bold text-slate-900", children: "Education Hub" }), _jsx("p", { className: "mt-3 text-slate-700", children: "Master the art of clear thinking, bullshit detection, and epistemic humility. Your journey to intellectual freedom starts here." }), _jsxs("div", { className: "mt-8 grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsx(Card, { to: "/educate/epistemic-foundations", title: "Epistemic Foundations", desc: "Build your foundation in critical thinking and intellectual humility.", icon: _jsx(Landmark, { className: "w-5 h-5" }) }), _jsx(Card, { to: "/educate/bullshit-detection", title: "Bullshit Detection", desc: "Identify manipulation, fallacies, and deceptive language.", icon: _jsx(ShieldCheck, { className: "w-5 h-5" }) }), _jsx(Card, { to: "/educate/logical-fallacies", title: "Logical Fallacies", desc: "Spot flawed reasoning and invalid arguments.", icon: _jsx(BookOpen, { className: "w-5 h-5" }) }), _jsx(Card, { to: "/educate/ai-awareness", title: "AI Awareness", desc: "Understand how AI systems work, fail, and can be manipulated.", icon: _jsx(Cpu, { className: "w-5 h-5" }) }), _jsx(Card, { to: "/educate/advanced-practice", title: "Advanced Practice", desc: "Master-level exercises in clarity, precision, and truth detection.", icon: _jsx(Trophy, { className: "w-5 h-5" }) }), _jsx(Card, { to: "/educate/bullshit-patterns", title: "Pattern Library", desc: "Search expert-identified rhetorical and semantic patterns.", icon: _jsx(Search, { className: "w-5 h-5" }) })] }), _jsx("h2", { className: "mt-10 text-xl font-semibold text-slate-900", children: "More modules" }), _jsxs("div", { className: "mt-4 grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsx(Card, { to: "/educate/clarity-signals", title: "Clarity Signals", desc: "Positive indicators of honest, careful communication.", icon: _jsx(Beaker, { className: "w-5 h-5" }) }), _jsx(Card, { to: "/educate/epistemic-sandbox", title: "Epistemic Sandbox", desc: "Interactive practice area for hypotheses, tests, and uncertainty.", icon: _jsx(Brain, { className: "w-5 h-5" }) }), _jsx(Card, { to: "/educate/how-llms-bullshit", title: "How LLMs Bullshit", desc: "Understand and counteract model tendencies toward overclaiming.", icon: _jsx(HelpCircle, { className: "w-5 h-5" }) }), _jsx(Card, { to: "/train", title: "Train an AI to be Honest", desc: "(Future) Teach models epistemic humility with guided prompts.", icon: _jsx(Cpu, { className: "w-5 h-5" }) })] }), _jsxs("blockquote", { className: "mt-10 p-5 rounded-2xl bg-[#e9eef5] italic text-slate-800", style: { boxShadow: "inset 6px 6px 12px #cfd6e0, inset -6px -6px 12px #ffffff" }, children: ["\u201CThe first principle is that you must not fool yourself \u2014 and you are the easiest person to fool.\u201D", _jsx("div", { className: "text-sm not-italic text-slate-600 mt-2", children: "\u2014 Richard Feynman" })] })] })] }) }));
};
export default EducateHub;
