import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { ShieldCheck, Beaker, Link2, Cpu, ArrowRight, Bot, GraduationCap } from "lucide-react";
import { buildHandshake } from "@/lib/codex-runtime";
import codex from "@/data/front-end-codex.v0.9.json";
const HandshakeStatus = () => {
    // Non-interactive status (read-only). Later we can add a Mode×Stakes switcher.
    const hs = buildHandshake(codex, { mode: "--careful", stakes: "medium" });
    return (_jsxs("div", { className: "text-xs md:text-sm text-slate-600 mt-2", children: [_jsx("span", { className: "font-medium", children: "Handshake" }), " \u00B7 mode=", _jsx("code", { children: hs.mode }), " \u00B7 stakes=", _jsx("code", { children: hs.stakes }), " \u00B7 min_confidence=", _jsx("code", { children: hs.min_confidence }), " \u00B7 cite_policy=", _jsx("code", { children: hs.cite_policy }), " \u00B7 omission_scan=", _jsx("code", { children: String(hs.omission_scan) }), " \u00B7 reflex_profile=", _jsx("code", { children: hs.reflex_profile })] }));
};
const IndexPage = () => {
    return (_jsx("main", { className: "min-h-screen bg-[#e9eef5] text-slate-800", children: _jsxs("section", { className: "max-w-6xl mx-auto px-6 py-16", children: [_jsxs("div", { className: "relative rounded-3xl p-10 md:p-14", style: {
                        background: "#e9eef5",
                        boxShadow: "9px 9px 18px rgba(163,177,198,0.6), -9px -9px 18px rgba(255,255,255,0.9)",
                    }, children: [_jsxs("div", { className: "flex flex-col gap-3", children: [_jsxs("div", { className: "inline-flex items-center text-xs md:text-sm text-slate-600", children: [_jsx(Cpu, { className: "w-4 h-4 mr-2" }), _jsx("span", { className: "font-semibold", children: "AWS Agent Ready" }), " \u00B7", _jsx("span", { className: "ml-1", children: "Codex v0.9 Handshake" })] }), _jsx("h1", { className: "text-3xl md:text-5xl font-extrabold tracking-tight text-slate-900", children: "Truth Serum + Clarity Armor" }), _jsx("p", { className: "text-base md:text-lg text-slate-700", children: "AI-powered epistemic truth detection. Analyze language, detect manipulation, and build clarity\u2014with agent-grade handshakes, context decay, and failure semantics." }), _jsx(HandshakeStatus, {})] }), _jsxs("div", { className: "mt-8 grid grid-cols-1 md:grid-cols-3 gap-6", children: [_jsxs(Link, { to: "/analyze", className: "group md:col-span-2 block rounded-2xl p-8 md:p-10 cursor-pointer transition-transform hover:scale-[1.01] focus:outline-none", style: {
                                        background: "#e9eef5",
                                        boxShadow: "inset 10px 10px 20px #cfd6e0, inset -10px -10px 20px #ffffff",
                                    }, "aria-label": "Open analyzer", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(ShieldCheck, { className: "w-6 h-6" }), _jsx("h3", { className: "text-2xl font-semibold", children: "Analyze Language" })] }), _jsxs("p", { className: "mt-3 text-sm md:text-base text-slate-700", children: ["Run the VX reflex engine with semantic & cluster detection. Also handles", " ", _jsx("strong", { children: "Scientific Paper Checks" }), " and ", _jsx("strong", { children: "Link & Article Audits" }), "."] }), _jsxs("div", { className: "mt-5 inline-flex items-center text-sm font-medium text-slate-900", children: ["Open analyzer", _jsx(ArrowRight, { className: "w-4 h-4 ml-1 transition-transform group-hover:translate-x-0.5" })] })] }), _jsxs(Link, { to: "/educate", className: "group block rounded-2xl p-6 cursor-pointer transition-transform hover:scale-[1.01] focus:outline-none", style: {
                                        background: "#e9eef5",
                                        boxShadow: "inset 8px 8px 16px #cfd6e0, inset -8px -8px 16px #ffffff",
                                    }, "aria-label": "Open education hub", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Beaker, { className: "w-5 h-5" }), _jsx("h3", { className: "text-xl font-semibold", children: "Education Hub" })] }), _jsx("p", { className: "mt-2 text-sm text-slate-700", children: "Learn critical-thinking patterns & rhetorical traps. Browse the pattern library, then apply them in the analyzer." }), _jsxs("div", { className: "mt-4 inline-flex items-center text-sm font-medium text-slate-900", children: ["Explore lessons", _jsx(ArrowRight, { className: "w-4 h-4 ml-1 transition-transform group-hover:translate-x-0.5" })] })] })] }), _jsxs("div", { className: "mt-6 grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs(Link, { to: "/wisdom", className: "group block rounded-2xl p-5 cursor-pointer transition-transform hover:scale-[1.01] focus:outline-none", style: {
                                        background: "#e9eef5",
                                        boxShadow: "inset 6px 6px 12px #cfd6e0, inset -6px -6px 12px #ffffff",
                                    }, "aria-label": "Visit Wisdom & Training", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Link2, { className: "w-5 h-5" }), _jsx("h3", { className: "text-lg font-semibold", children: "Wisdom & Training" })] }), _jsx("p", { className: "mt-2 text-sm text-slate-700", children: "Curated quotes and drills for epistemic humility. Practice better questions and answers." }), _jsxs("div", { className: "mt-3 inline-flex items-center text-sm font-medium text-slate-900", children: ["Visit quotes", _jsx(ArrowRight, { className: "w-4 h-4 ml-1 transition-transform group-hover:translate-x-0.5" })] })] }), _jsxs(Link, { to: "/train", className: "group block rounded-2xl p-5 cursor-pointer transition-transform hover:scale-[1.01] focus:outline-none", style: {
                                        background: "#e9eef5",
                                        boxShadow: "inset 6px 6px 12px #cfd6e0, inset -6px -6px 12px #ffffff",
                                    }, "aria-label": "Open Train an AI page", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(GraduationCap, { className: "w-5 h-5" }), _jsx("h3", { className: "text-lg font-semibold", children: "Train an AI" })] }), _jsx("p", { className: "mt-2 text-sm text-slate-700", children: "Copy the codex & handshakes to teach AIs epistemic humility (v0.8 & v0.9)." }), _jsxs("div", { className: "mt-3 inline-flex items-center text-sm font-medium text-slate-900", children: ["Open training tools", _jsx(ArrowRight, { className: "w-4 h-4 ml-1 transition-transform group-hover:translate-x-0.5" })] })] })] }), _jsx("p", { className: "mt-10 text-sm italic text-slate-600", children: "\u201CClarity is kindness. Truth is a team sport.\u201D \u2014 Clarity Armor" })] }), _jsx("div", { className: "mt-12 max-w-6xl mx-auto px-2 md:px-0", children: _jsxs("div", { className: "grid md:grid-cols-3 gap-6 text-slate-700", children: [_jsxs("div", { children: [_jsxs("h4", { className: "font-semibold flex items-center gap-2", children: [_jsx(Bot, { className: "w-4 h-4" }), " VX Reflex Engine"] }), _jsx("p", { className: "text-sm mt-1", children: "Semantic patterns, co-fire clusters, adaptive thresholds." })] }), _jsxs("div", { children: [_jsxs("h4", { className: "font-semibold flex items-center gap-2", children: [_jsx(Beaker, { className: "w-4 h-4" }), " Scientific Paper Checks"] }), _jsx("p", { className: "text-sm mt-1", children: "Methods & references triage; conflict-of-interest cues." })] }), _jsxs("div", { children: [_jsxs("h4", { className: "font-semibold flex items-center gap-2", children: [_jsx(Cpu, { className: "w-4 h-4" }), " Agent-grade Handshake"] }), _jsx("p", { className: "text-sm mt-1", children: "mode, stakes, min_conf, cite_policy, omission_scan, profile." })] })] }) })] }) }));
};
export default IndexPage;
