import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import { VXProvider } from "@/context/VXProvider";
import HomePage from "@/pages/index";
import Educate from "@/pages/educate";
import EpistemicFoundations from "@/pages/educate/epistemic-foundations";
import BullshitDetection from "@/pages/educate/bullshit-detection";
import LogicalFallacies from "@/pages/educate/logical-fallacies";
import AIAwareness from "@/pages/educate/ai-awareness";
import AdvancedPractice from "@/pages/educate/advanced-practice";
import Analyze from "@/pages/analyze";
import Wisdom from "@/pages/wisdom";
import Train from "@/pages/train";
import Paper from "@/pages/paper";
import BotDetection from "@/pages/bot-detection";
import Omissions from "@/pages/omissions";
import BullshitPatterns from "@/pages/educate/bullshit-patterns";
import Testing from "@/pages/testing";
import VaguenessLesson from "@/pages/educate/vagueness";
import EmotionalFramingLesson from "@/pages/educate/emotional-framing";
import SpeculativeAuthorityLesson from "@/pages/educate/speculative-authority";
import HowLLMsBullshitLesson from "@/pages/educate/how-llms-bullshit";
import AIAwareLesson from "@/pages/educate/ai-aware";
import CitationLaunderingLesson from "@/pages/educate/bullshit-types/citation-laundering";
import EpistemicSandboxLesson from "@/pages/educate/epistemic-sandbox";
import ClaritySignalsPage from "@/pages/educate/clarity-signals";
import CertaintyVsTrust from "@/pages/educate/certainty-vs-trust";
import CognitiveDissonance from "@/pages/educate/cognitive-dissonance";
import ConfirmationBias from "@/pages/educate/confirmation-bias";
import EpistemicHumility from "@/pages/educate/epistemic-humility";
import MentalModels from "@/pages/educate/mental-models";
import NarrativeFraming from "@/pages/educate/narrative-framing";
import WhyCertaintySells from "@/pages/educate/why-certainty-sells";
import DetectBullshit from "@/pages/educate/detect-bullshit";
import JargonOverload from "@/pages/educate/jargon-overload";
import FalseUrgencyLesson from "@/pages/educate/false-urgency";
import AppealToAuthorityLesson from "@/pages/educate/appeal-to-authority";
import AppealToEmotionLesson from "@/pages/educate/appeal-to-emotion";
import FallaciesOverview from "@/pages/educate/fallacies-overview";
import FalseDichotomy from "@/pages/educate/false-dichotomy";
import FalseDilemma from "@/pages/educate/false-dilemma";
import RedHerring from "@/pages/educate/red-herring";
import StrawMan from "@/pages/educate/straw-man";
import Steelman from "@/pages/educate/steelman";
import AdHominem from "@/pages/educate/ad-hominem";
import CircularReasoning from "@/pages/educate/circular-reasoning";
import BecomeAIAware from "@/pages/educate/become-ai-aware";
import NarrativeFramingAnalysis from "@/pages/educate/narrative-framing-analysis";
import AIBehaviorPatterns from "@/pages/educate/ai-behavior-patterns";
const App = () => {
    return (_jsx(VXProvider, { children: _jsx(Router, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(HomePage, {}) }), _jsx(Route, { path: "/educate", element: _jsx(Educate, {}) }), _jsx(Route, { path: "/educate/epistemic-foundations", element: _jsx(EpistemicFoundations, {}) }), _jsx(Route, { path: "/educate/bullshit-detection", element: _jsx(BullshitDetection, {}) }), _jsx(Route, { path: "/educate/logical-fallacies", element: _jsx(LogicalFallacies, {}) }), _jsx(Route, { path: "/educate/ai-awareness", element: _jsx(AIAwareness, {}) }), _jsx(Route, { path: "/educate/advanced-practice", element: _jsx(AdvancedPractice, {}) }), _jsx(Route, { path: "/educate/vagueness", element: _jsx(VaguenessLesson, {}) }), _jsx(Route, { path: "/educate/emotional-framing", element: _jsx(EmotionalFramingLesson, {}) }), _jsx(Route, { path: "/educate/speculative-authority", element: _jsx(SpeculativeAuthorityLesson, {}) }), _jsx(Route, { path: "/educate/how-llms-bullshit", element: _jsx(HowLLMsBullshitLesson, {}) }), _jsx(Route, { path: "/educate/ai-aware", element: _jsx(AIAwareLesson, {}) }), _jsx(Route, { path: "/educate/bullshit-types/citation-laundering", element: _jsx(CitationLaunderingLesson, {}) }), _jsx(Route, { path: "/educate/epistemic-sandbox", element: _jsx(EpistemicSandboxLesson, {}) }), _jsx(Route, { path: "/educate/clarity-signals", element: _jsx(ClaritySignalsPage, {}) }), _jsx(Route, { path: "/educate/certainty-vs-trust", element: _jsx(CertaintyVsTrust, {}) }), _jsx(Route, { path: "/educate/cognitive-dissonance", element: _jsx(CognitiveDissonance, {}) }), _jsx(Route, { path: "/educate/confirmation-bias", element: _jsx(ConfirmationBias, {}) }), _jsx(Route, { path: "/educate/epistemic-humility", element: _jsx(EpistemicHumility, {}) }), _jsx(Route, { path: "/educate/mental-models", element: _jsx(MentalModels, {}) }), _jsx(Route, { path: "/educate/narrative-framing", element: _jsx(NarrativeFraming, {}) }), _jsx(Route, { path: "/educate/why-certainty-sells", element: _jsx(WhyCertaintySells, {}) }), _jsx(Route, { path: "/educate/detect-bullshit", element: _jsx(DetectBullshit, {}) }), _jsx(Route, { path: "/educate/jargon-overload", element: _jsx(JargonOverload, {}) }), _jsx(Route, { path: "/educate/false-urgency", element: _jsx(FalseUrgencyLesson, {}) }), _jsx(Route, { path: "/educate/appeal-to-authority", element: _jsx(AppealToAuthorityLesson, {}) }), _jsx(Route, { path: "/educate/appeal-to-emotion", element: _jsx(AppealToEmotionLesson, {}) }), _jsx(Route, { path: "/educate/fallacies-overview", element: _jsx(FallaciesOverview, {}) }), _jsx(Route, { path: "/educate/false-dichotomy", element: _jsx(FalseDichotomy, {}) }), _jsx(Route, { path: "/educate/false-dilemma", element: _jsx(FalseDilemma, {}) }), _jsx(Route, { path: "/educate/red-herring", element: _jsx(RedHerring, {}) }), _jsx(Route, { path: "/educate/straw-man", element: _jsx(StrawMan, {}) }), _jsx(Route, { path: "/educate/steelman", element: _jsx(Steelman, {}) }), _jsx(Route, { path: "/educate/ad-hominem", element: _jsx(AdHominem, {}) }), _jsx(Route, { path: "/educate/circular-reasoning", element: _jsx(CircularReasoning, {}) }), _jsx(Route, { path: "/educate/become-ai-aware", element: _jsx(BecomeAIAware, {}) }), _jsx(Route, { path: "/educate/narrative-framing-analysis", element: _jsx(NarrativeFramingAnalysis, {}) }), _jsx(Route, { path: "/educate/ai-behavior-patterns", element: _jsx(AIBehaviorPatterns, {}) }), _jsx(Route, { path: "/analyze", element: _jsx(Analyze, {}) }), _jsx(Route, { path: "/wisdom", element: _jsx(Wisdom, {}) }), _jsx(Route, { path: "/train", element: _jsx(Train, {}) }), _jsx(Route, { path: "/paper", element: _jsx(Paper, {}) }), _jsx(Route, { path: "/bot-detection", element: _jsx(BotDetection, {}) }), _jsx(Route, { path: "/omissions", element: _jsx(Omissions, {}) }), _jsx(Route, { path: "/educate/bullshit-patterns", element: _jsx(BullshitPatterns, {}) }), _jsx(Route, { path: "/testing", element: _jsx(Testing, {}) })] }) }) }));
};
export default App;
